name: Lockdown
main: com.minecarts.lockdown.Lockdown
version: ${pom.version}
website: http://minecarts.com
author: Minecarts.com
description: >
             Lockdown the world to prevent any changes until it's disabled by another plugin
commands:
    lockdown:
        description: Main command for admins to manage the locked state
        usage: /<command> [lock | unlock]
permissions:
    lockdown.bypass_lock:
        description: "Bypass *certain* lockdown attributes such as login lock"
        default: op